import type { Locale } from '../i18n/useLocale';
import type { Narrative } from '../data/narrativeData';

// Renders the LLM-generated narrative (model judgement / validated + under-weighted
// signals / takeaway / operator copy) as the customer main view. The provenance and
// internal notes live in a collapsed block. Engineering only renders; the words are
// the model's. vi/mm fall back to English labels (never Chinese).
const NV_LABELS = {
  zh: { judgement: 'Giành Cup AI 怎么看', validated: '模型抓对的风险', underweighted: '被低估 · 下一版需补强',
        takeaway: '下一场该看什么', operator: '运营可发文案', internal: '内部资料 / 来源（点击展开）', by: '本段由模型生成' },
  vi: { judgement: 'Giành Cup AI nhìn thế nào', validated: 'Rủi ro mô hình đã bắt đúng', underweighted: 'Bị đánh giá thấp · cần bổ sung',
        takeaway: 'Lần sau nên xem gì', operator: 'Nội dung cho vận hành', internal: 'Tài liệu nội bộ / nguồn (nhấn để mở)', by: 'Phần này do mô hình tạo' },
  en: { judgement: 'How Giành Cup AI reads it', validated: 'Risks the model flagged', underweighted: 'Under-weighted · add next',
        takeaway: 'What to watch next', operator: 'Operator-ready copy', internal: 'Internal notes / sources (expand)', by: 'Generated by the model' },
};

export function NarrativeView({ narrative: n, loc }: { narrative: Narrative; loc: Locale }) {
  const L = loc === 'zh' ? NV_LABELS.zh : loc === 'vi' ? NV_LABELS.vi : NV_LABELS.en;
  return (
    <>
      <div className="sec-en"><span className="zh">{L.judgement}</span><span className="en">AI READ</span></div>
      <div className="card"><p className="eb-lead">{n.model_judgement}</p></div>

      <div className="sec-en"><span className="zh">{L.validated}</span><span className="en">VALIDATED</span></div>
      <div className="card">
        {n.validated_signals.map((s, i) => (
          <div className="nv-signal" key={i}><div className="nv-name">{s.name}</div><div className="nv-text">{s.text}</div></div>
        ))}
      </div>

      <div className="sec-en"><span className="zh">{L.underweighted}</span><span className="en">UNDER-WEIGHTED</span></div>
      <div className="card">
        {n.underweighted_signals.map((s, i) => (
          <div className="nv-signal" key={i}><div className="nv-name">{s.name}</div><div className="nv-text">{s.text}</div></div>
        ))}
      </div>

      <div className="sec-en"><span className="zh">{L.takeaway}</span><span className="en">WATCH NEXT</span></div>
      <div className="card"><p className="eb-lead">{n.customer_takeaway}</p></div>

      <div className="sec-en"><span className="zh">{L.operator}</span><span className="en">OPERATOR COPY</span></div>
      <div className="card"><div className="recap-copybox">{n.operator_copy}</div></div>

      {/* internal — model provenance + notes (collapsed, never the customer headline) */}
      <details className="card recap-ledger eb-internal">
        <summary>{L.internal}</summary>
        {n.internal_notes.map((x, i) => <div className="eb-internal-line" key={i}>· {x}</div>)}
        <div className="nv-prov">{L.by}: {n.llm_provider}{n.model ? ' · ' + n.model : ''}</div>
      </details>
    </>
  );
}
