// Customer-safe EXTERNAL EXPECTATION projection (engineering stage data).
// Generated by scripts/mvp2_project_external_signals.py from the INTERNAL signal
// frame (docs/data_audit/mvp2_external_signals/, never bundled). Only recorded
// signals project; phrasing is the fixed Owner-approved customer-safe vocabulary
// (外部预期 / 公开预测倾向 / 热度集中…) — no sources, no prices, no odds/betting
// words, rumors only as conditional "锋线核心" phrasing pending the official XI.
// DO NOT hand-edit the JSON; re-run the projection script.
import type { Locale } from '../i18n/useLocale';
import s1489371 from './externalSignals/1489371.json';

export interface ExternalSignalProjection {
  fixture_id: string;
  label: Record<string, string>;
  lines: Record<string, string[]>;
}

const ALL: Record<string, ExternalSignalProjection> = {
  '1489371': s1489371 as ExternalSignalProjection,
};

export function getExternalSignals(fixtureId: string, loc: Locale): { label: string; lines: string[] } | null {
  const p = ALL[fixtureId];
  if (!p) return null;
  const lang = loc === 'zh' || loc === 'vi' || loc === 'my' ? loc : null;
  if (!lang) return null; // en = internal fallback layer, no projection surface
  const lines = p.lines[lang] ?? [];
  if (!lines.length) return null;
  return { label: p.label[lang] ?? '', lines };
}
