/**
 * English (en) copy — the international fallback for all non-Chinese locales.
 *
 * vi (and future mm) fall back to EN, never to Chinese, to avoid mixed-language
 * UI. Must cover every key in the dictionary's `Copy` type. Price-bearing strings
 * are LABEL-ONLY; the actual price comes from `i18n/pricing.ts`.
 */
import type { Copy } from '../i18n/dict';

export const EN: Copy = {
  // Header / brand
  brandName: 'Giành Cup',
  brandRole: 'World Cup AI Football Intelligence Community',
  headerSub: 'Not just odds — understand why the AI decides this way.',
  brandHeroEn: '2026 World Cup AI Football Intelligence',

  // Bottom nav
  navHome: 'Home',
  navDetail: 'AI Pick',
  navToken: 'MTC',
  navCommunity: 'Community',

  // Global
  aiTicker: 'AI Intel',
  tickerBody: 'AI intel update · {n} pre-match models today · {live} in live watch · synced {time} · AI keeps tracking lineups and live variables',
  apiErrorCache: '⚠️ Using locally cached data (intel source temporarily unavailable)',
  syncLabel: 'Synced',
  loadingText: 'Loading AI intel…',

  // Hero
  heroTitlePre: 'Football ',
  heroTitleAccent: 'AI Intel',
  heroSub: 'AI viewpoint · Odds shift · Risk note · Live correction',

  // Capability chips
  capModel: 'AI pre-match model',
  capLive: 'Live 30-min correction',
  capRisk: 'Risk rating',
  capUnlock: 'MTC unlock',

  // Balance / check-in
  balanceLabel: 'My MTC fan points: ',
  checkin: 'Check in +10',
  checkedIn: 'Checked in',
  checkinToastDone: 'Already checked in today',
  checkinToastOk: 'Checked in +10 MTC',

  // Home core + CTA
  signalTitle: "Today's strongest AI signal",
  tendency: 'AI trend',
  topRisk: 'Key risk',
  ctaView: 'View AI viewpoint',
  ctaUnlock: 'Unlock full analysis',
  winLabel: 'win',

  // Section titles + states
  listTitle: "Today's matches",
  upsetTitle: 'Top 3 upset risks today',
  recordTitle: 'AI intel track record',
  heatTitle: 'Community picks',
  loopTitle: 'Fan zone',
  recordPending: 'Opens after real results sync',
  recordBuilding: 'Building data capability',
  recordSub: 'Hit-rate and streak metrics open after connecting a real data source and syncing results.',
  heatComingSoon: 'Community heat coming soon',
  heatSub: 'Community discussion heat and user attention trends are being built.',
  heatNote: 'Community heat is anonymous in-app interaction stats; no personal info.',
  heatAttention: '🔥 Community attention',
  interactions: 'Interactions',
  upsetScoreLabel: 'Upset score',
  upsetHookHigh: 'Upset risk rising',
  upsetHookMid: 'Watch with caution',
  upsetHookLow: 'Risk under control',
  loopFanPoints: 'Fan points',
  loopDailyCheckin: 'Daily check-in',
  loopStreak: 'Streak challenge',
  loopFreeJoin: 'Join free',
  loopRanking: 'Rankings',
  loopComingSoon: 'Coming soon',
  rankingComingToast: 'Rankings coming soon',

  // Detail
  detailBack: 'Match prediction detail',
  aiVerdict: 'AI verdict',
  confidence: 'Confidence',
  riskGrade: 'Risk level',
  recommendedScore: 'Suggested score',
  unlockToView: 'Unlock to view',
  winProbTitle: 'AI current win probability',
  whyTitle: 'Why the AI decides this',
  riskTitle: 'Risk factors',
  confIndex: 'Confidence index',
  lineupWatchTitle: '📡 LINEUP WATCH · Live monitor',
  lwRecalc: 'Recalculated',
  lwArmed: 'Armed',
  lwStep1: 'Auto-enter\nwatch pre-match',
  lwStep2: 'After release\ntrigger recalc',
  lwStep3: 'Odds update\nwith variables',
  lwBodyDefault: 'Auto-enters watch 60 min before kickoff. After the lineup is released, the AI recalculates odds based on key players, formation changes and bench strength.',
  lwCorrectionPrefix: '[Live correction] ',
  lwRecalcMid: ', model recalculates: ',
  lwDrawWord: 'Draw',
  lwReasonWord: 'Reason: ',
  lwRateWord: 'win prob',
  lwBtnDone: 'Recalculated by lineup ✓',
  lwBtnDo: 'Simulate lineup release → AI recalc',
  premiumTitle: 'AI tactical insight',
  premiumLocked: '🔒 Locked',
  premiumUnlockHint: 'Unlock to view the full model explanation',
  unlockCashLabel: 'Unlock AI tactical insight',
  unlockMtcLabel: '🪙 View full model explanation',
  balanceSuffix: ' (balance {balance})',
  joinCommunityLabel: 'Join the live intelligence community',
  payOkTitle: 'Mock payment succeeded',
  payFailTitle: 'Payment failed',
  mtcDeductedTitle: '390 MTC deducted',
  mtcInsufficient: 'Not enough MTC — light up a match day in the fan center',
  liveToastPrefix: 'Live correction: ',
  liveToastRate: 'win prob',

  // Token
  tokenBack: '🪙 Fan mission center',
  walletLabel: 'My MTC fan-point balance',
  lastUpdate: 'Last update',
  myStreak: 'My streak',
  curStreak: 'Current streak',
  bestStreak: 'Best streak',
  challengeMtc: 'MTC from challenges',
  streakBuilding: 'Streak challenge in progress',
  streakBuildingSub: 'After you join free prediction challenges and they settle post-match, your streak and MTC progress show here.',
  dailyMissions: 'Daily missions',
  missionCheckinT: 'Daily check-in',
  missionCheckinD: 'Light up today’s match day, stay in the loop',
  missionShareT: 'Share a prediction card',
  missionShareD: 'Bring friends into the intel station',
  missionInviteT: 'Invite friends to sign up',
  missionInviteD: 'Grow your intel squad',
  missionDone: 'Done',
  predictionChallenge: 'Prediction challenge',
  challengeTitle: 'Brazil vs Argentina · Test your read with points',
  challengeQ: 'Will there be a red card? · Join free · Correct picks share MTC points',
  challengeYes: 'A. Yes',
  challengeNo: 'B. No',
  challengeJoinedToast: 'Joined the free prediction challenge',
  challengeJoinedMsgPre: '✔ Joined the free challenge (picked “',
  challengeJoinedMsgPost: '”) · Settles post-match, sharing the point reward',
  shopTitle: 'Redeem points',
  shopReport: 'Single-match AI deep report',
  shopCommunity7: '7-day community trial',
  shopFreepass: 'Single-match free pass',
  rankingsTitle: 'Streak rankings',
  rankStreakWord: 'Streak',
  rankingsBuilding: 'Rankings in progress',
  rankingsBuildingSub: 'Streak and MTC rankings open after challenges accumulate; shows points/participation/streak only, not an earnings board.',
  rankingsDisclaimerPre: 'A points/streak board, not an earnings board. ',
  tokenMtcCompliance: '⚠️ MTC fan points are platform points only: non-withdrawable · non-transferable · non-tradable · no profit promise · not a financial asset · no betting.',
  tokenInsufficient: 'Not enough MTC',

  // Community
  communityBack: '👥 Live Intelligence VIP',
  vipKicker: 'Live Intelligence VIP',
  vipPriceSub: 'You get not a single prediction, but a full match-intel stream.',
  communityTitle: 'Community matrix',
  statusComingSoon: 'Coming soon',
  statusActive: 'Open',
  statusDisabled: 'Not open',
  intelFlowTitle: 'A full intel stream',
  flow1T: 'Pre-match model read',
  flow1D: 'Win-probability spread, suggested score, risk rating and key factors per match.',
  flow2T: 'Live lineup correction',
  flow2D: 'Within 30 min of lineup release, the AI recalculates and pushes the shift.',
  flow3T: 'Post-match model review',
  flow3D: 'Compare the model read with the real result; refine the next match’s view.',
  benefitsTitle: 'Member benefits',
  benefit1: 'AI intel push for 3-5 matches daily',
  benefit2: 'Full model explanation per match',
  benefit3: 'AI recalculation within 30 min of lineup release',
  benefit4: 'Real-time live-correction push',
  benefit5: 'High-risk match alerts',
  benefit6: 'MTC point boost',
  benefit7: 'Private community service',
  whyVipTitle: 'Why is the community worth it?',
  whyVipExample: 'Real-time shift example',
  whyVipHomeRate: 'Brazil win prob',
  whyVipReason: 'Argentina’s key center-back out → Brazil’s right-flank edge grows; the community gets the push first.',
  csTitle: 'AI content studio',
  csStatus: 'Building data capability',
  csItem1: "Today's 3-match AI quick view",
  csItem2: "Today's highest confidence",
  csItem3: 'Upset-risk short graphic',
  csItem4: 'Live-correction screenshot',
  csItem5: 'Post-match review long graphic',
  csItem6: 'Community push copy',
  csAction1: 'Copy operations text (coming soon)',
  csAction2: 'Generate share card (coming soon)',
  storageConnected: 'Asset storage connected',
  storagePublicEnabled: 'Public asset access enabled',
  storagePublicPending: 'Public domain pending',
  storageChecking: 'Confirming storage status',
  subscribeNowLabel: 'Subscribe now',
  subscribedLabel: '✓ Subscribed · live push enabled',
  subscribedToast: 'Subscribed · live push enabled',
  alreadySubscribed: 'Already subscribed',
  communityMutedNote: 'Subscription is an AI data-analysis & intel service · not betting · no cash wagering · MTC non-withdrawable',

  // Compliance
  mtcStatement: 'MTC is a platform loyalty point — non-withdrawable, non-transferable, non-tradable, and not a financial asset.',
  disclaimer: 'Past performance does not guarantee future results. Content is for data analysis and football entertainment only.',
  complianceFooter: 'AI data analysis only · not a betting service · no cash wagering · MTC non-withdrawable',

  // Vietnamese trial badge (bilingual; same in all locales)
  viBadge: '越南语试跑文案已就绪 · Đã chuẩn bị nội dung thử nghiệm tiếng Việt',
};
