/**
 * Burmese / Myanmar (mm) copy — customer-ready MVP (operation-accepted).
 *
 * Upgraded from "framework + English fallback" to broad customer-ready Burmese.
 * Style: short Burmese with concise English product terms kept (AI / MTC /
 * Update / Premium / VIP / team names), matching the apolloveo-auto mm style.
 * Any key not present here still falls back to English (never Chinese) via the
 * dictionary chain (mm → en). Density profile `.lang-mm` keeps layout compact.
 */
import type { Copy } from '../i18n/dict';

export const MM: Partial<Copy> = {
  // Header / brand
  brandRole: 'AI Football',
  headerSub: 'AI သုံးသပ်ချက် · ပွဲမတိုင်ခင် အချက်အလက်',

  // Bottom nav
  navHome: 'မူလ',
  navDetail: 'AI',
  navToken: 'MTC',
  navCommunity: 'အသိုင်းအဝိုင်း',

  // Global
  aiTicker: 'AI သတင်း',
  tickerBody: 'AI သတင်း · ယနေ့ မော်ဒယ် {n} ခု · တိုက်ရိုက်စောင့်ကြည့်',
  apiErrorCache: '⚠️ ဒေသတွင်း cache ဒေတာသုံးနေသည် (သတင်းရင်းမြစ် ယာယီမရနိုင်)',
  syncLabel: 'ထပ်တူ',
  loadingText: 'AI သတင်း ဖွင့်နေသည်…',

  // Hero
  heroTitlePre: 'AI ဘောလုံး',
  heroTitleAccent: 'အချက်အလက်',
  heroSub: 'ဖြစ်နိုင်ခြေ · အန္တရာယ် · 30′ update',

  // Capability chips
  capModel: 'AI မော်ဒယ်',
  capLive: '30′ Update',
  capRisk: 'အန္တရာယ်',
  capUnlock: 'MTC',

  // Balance / check-in
  balanceLabel: 'ကျွန်ုပ်၏ MTC ပွိုင့်: ',
  checkin: 'အမှတ်ယူ +10',
  checkedIn: 'ယူပြီး',
  checkinToastDone: 'ယနေ့ ယူပြီးပါပြီ',
  checkinToastOk: 'အမှတ်ယူအောင်မြင် +10 MTC',

  // Home core + CTA
  signalTitle: 'AI signal',
  tendency: 'AI အမြင်',
  topRisk: 'အန္တရာယ်',
  ctaView: 'AI အမြင်',
  ctaUnlock: 'အပြည့်အစုံ ကြည့်ရန်',
  winLabel: 'နိုင်',

  // Section titles + states
  listTitle: 'ယနေ့ ပွဲများ',
  upsetTitle: 'အံ့အားသင့် TOP3',
  recordTitle: 'AI မှတ်တမ်း',
  heatTitle: 'အသိုင်းအဝိုင်း',
  loopTitle: 'ပရိသတ် Zone',
  recordPending: 'တကယ့်ရလဒ်ပြီးမှ ဖွင့်မည်',
  recordBuilding: 'ဒေတာ တည်ဆောက်နေဆဲ',
  recordSub: 'အောင်နှုန်းနှင့် ဆက်တိုက်အောင်မှတ်များကို တကယ့်ဒေတာ ချိတ်ပြီး ရလဒ်ဖြည့်ပြီးနောက် ဖွင့်မည်။',
  heatComingSoon: 'အသိုင်းအဝိုင်း ပူပြင်းမှု မကြာမီ',
  heatSub: 'အသိုင်းအဝိုင်း ဆွေးနွေးမှုနှင့် စိတ်ဝင်စားမှု လမ်းကြောင်း တည်ဆောက်နေဆဲ။',
  heatNote: 'အသိုင်းအဝိုင်း ပူပြင်းမှုသည် အမည်ဝှက် အပြန်အလှန် အရေအတွက်သာ၊ ကိုယ်ရေးအချက်အလက် မပါ။',
  heatAttention: '🔥 အသိုင်းအဝိုင်း စိတ်ဝင်စား',
  interactions: 'အပြန်အလှန်',
  upsetScoreLabel: 'အံ့အားသင့်အမှတ်',
  upsetHookHigh: 'အံ့အားသင့်နိုင်ခြေ မြင့်',
  upsetHookMid: 'သတိထားရန်',
  upsetHookLow: 'အန္တရာယ် ထိန်းနိုင်',
  loopFanPoints: 'ပရိသတ်ပွိုင့်',
  loopDailyCheckin: 'နေ့စဉ် အမှတ်ယူ',
  loopStreak: 'ဆက်တိုက်နိုင်ပွဲ',
  loopFreeJoin: 'အခမဲ့ ပါဝင်',
  loopRanking: 'အဆင့်စာရင်း',
  loopComingSoon: 'မကြာမီ',
  rankingComingToast: 'အဆင့်စာရင်း မကြာမီ',

  // Detail
  detailBack: 'ပွဲ ခန့်မှန်းချက် အသေးစိတ်',
  aiVerdict: 'AI ကောက်ချက်',
  confidence: 'ယုံကြည်မှု',
  riskGrade: 'အန္တရာယ်အဆင့်',
  recommendedScore: 'အကြံပြု ရမှတ်',
  unlockToView: 'ဖွင့်ကြည့်ရန်',
  winProbTitle: 'AI နိုင်ခြေ',
  whyTitle: 'AI သုံးသပ်ချက်',
  riskTitle: 'အန္တရာယ်အချက်များ',
  confIndex: 'ယုံကြည်မှု',
  lineupWatchTitle: '📡 လူစာရင်း စောင့်ကြည့်မှု',
  lwRecalc: 'ပြန်တွက်ပြီး',
  lwArmed: 'စောင့်ဆိုင်း',
  lwStep1: 'ပွဲမတိုင်ခင်\nအလိုအလျောက်စောင့်',
  lwStep2: 'ထွက်ပြီးနောက်\nပြန်တွက်',
  lwStep3: 'အချက်များအရ\nနိုင်ခြေ update',
  lwBodyDefault: 'ပွဲမတိုင်ခင် ၆၀ မိနစ်တွင် အလိုအလျောက် စောင့်ကြည့်သည်။ လူစာရင်းထွက်ပြီးနောက် အဓိကကစားသမား၊ ဖွဲ့စည်းပုံနှင့် အရန်အင်အားအရ AI က နိုင်ခြေ ပြန်တွက်သည်။',
  lwCorrectionPrefix: '【တိုက်ရိုက်ပြင်ဆင်ချက်】',
  lwRecalcMid: '၊ မော်ဒယ် ပြန်တွက်: ',
  lwDrawWord: 'သရေ',
  lwReasonWord: 'အကြောင်းရင်း: ',
  lwRateWord: 'နိုင်ခြေ',
  lwBtnDone: 'လူစာရင်းအရ ပြန်တွက်ပြီး ✓',
  lwBtnDo: 'လူစာရင်းထွက်သည်ဟု စမ်း → AI ပြန်တွက်',
  premiumTitle: 'AI နည်းဗျူဟာ',
  premiumLocked: '🔒 ပိတ်ထားသည်',
  premiumUnlockHint: 'မော်ဒယ် ရှင်းလင်းချက် အပြည့်အစုံ ဖွင့်ရန်',
  unlockCashLabel: 'AI နည်းဗျူဟာ ဖွင့်ရန်',
  unlockMtcLabel: '🪙 အပြည့်အစုံ ခွဲခြမ်းစိတ်ဖြာမှု',
  balanceSuffix: ' (လက်ကျန် {balance})',
  joinCommunityLabel: 'အသိုင်းအဝိုင်းသို့ ဝင်ရန်',
  payOkTitle: 'စမ်းသပ် ငွေပေးချေမှု အောင်မြင်',
  payFailTitle: 'ငွေပေးချေမှု မအောင်မြင်',
  mtcDeductedTitle: 'MTC 390 နုတ်ယူပြီး',
  mtcInsufficient: 'MTC မလုံလောက်ပါ၊ တာဝန်စင်တာတွင် ပွဲနေ့ ဖွင့်ပါ',
  unlockedBody: 'ဖွင့်ပြီးပါပြီ။ အစီရင်ခံစာအပြည့်အစုံကို ကြည့်နိုင်ပါသည်။',
  unlockFailedBody: 'ဖွင့်၍မရပါ၊ ခဏနေ ပြန်ကြိုးစားပါ။',
  continueToReport: 'အစီရင်ခံစာ ဆက်ကြည့်ရန်',
  liveToastPrefix: 'တိုက်ရိုက်ပြင်ဆင်ချက်: ',
  liveToastRate: 'နိုင်ခြေ',

  // Token
  tokenBack: '🪙 ပရိသတ် Zone',
  walletLabel: 'ကျွန်ုပ်၏ MTC လက်ကျန်',
  lastUpdate: 'နောက်ဆုံး update',
  myStreak: 'ကျွန်ုပ်၏ ဆက်တိုက်နိုင်ပွဲ',
  curStreak: 'လက်ရှိ ဆက်တိုက်',
  bestStreak: 'အကောင်းဆုံး ဆက်တိုက်',
  challengeMtc: 'Challenge မှ MTC',
  streakBuilding: 'ဆက်တိုက်နိုင်ပွဲ တည်ဆောက်နေဆဲ',
  streakBuildingSub: 'အခမဲ့ ခန့်မှန်း Challenge ပါဝင်ပြီး ပွဲပြီးနောက် ရှင်းတမ်းပြီးမှ သင့်ဆက်တိုက်နှင့် MTC တိုးတက်မှုကို ဤနေရာ ပြမည်။',
  dailyMissions: 'နေ့စဉ် တာဝန်',
  missionCheckinT: 'နေ့စဉ် အမှတ်ယူ',
  missionCheckinD: 'ယနေ့ ပွဲနေ့ ဖွင့်ပြီး သတင်း update ထား',
  missionShareT: 'ခန့်မှန်းကတ် မျှဝေ',
  missionShareD: 'သူငယ်ချင်းကို ဖိတ်ခေါ်',
  missionInviteT: 'သူငယ်ချင်း ဖိတ်ရန်',
  missionInviteD: 'သင့်အသင်း တိုးချဲ့',
  missionDone: 'ပြီးပြီ',
  predictionChallenge: 'ခန့်မှန်း Challenge',
  challengeTitle: 'Brazil vs Argentina · ပွိုင့်ဖြင့် သင့်ခန့်မှန်း စမ်းပါ',
  challengeQ: 'ဤပွဲတွင် အနီကတ် ရှိမလား? · အခမဲ့ ပါဝင် · မှန်လျှင် MTC အတူ ခွဲဝေ',
  challengeYes: 'A. ရှိ',
  challengeNo: 'B. မရှိ',
  challengeJoinedToast: 'အခမဲ့ ခန့်မှန်း Challenge ပါဝင်ပြီး',
  challengeJoinedMsgPre: '✔ အခမဲ့ Challenge ပါဝင်ပြီး (ရွေး「',
  challengeJoinedMsgPost: '」) · ပွဲပြီးနောက် ရှင်းတမ်း၊ ပွိုင့် အတူ ခွဲဝေ',
  shopTitle: 'MTC Shop',
  shopReport: 'တစ်ပွဲ AI အသေးစိတ် report',
  shopCommunity7: 'အသိုင်းအဝိုင်း ၇ ရက် စမ်း',
  shopFreepass: 'တစ်ပွဲ အခမဲ့ pass',
  rankingsTitle: 'ဆက်တိုက်နိုင်ပွဲ အဆင့်စာရင်း',
  rankStreakWord: 'ဆက်တိုက်',
  rankingsBuilding: 'အဆင့်စာရင်း တည်ဆောက်နေဆဲ',
  rankingsBuildingSub: 'ဆက်တိုက်နိုင်ပွဲနှင့် MTC အဆင့်စာရင်းကို Challenge ရှင်းတမ်း စုဆောင်းပြီးမှ ဖွင့်မည်; ပွိုင့်/ပါဝင်မှု/ဆက်တိုက်သာ ပြသည်၊ ဝင်ငွေဇယား မဟုတ်ပါ။',
  rankingsDisclaimerPre: 'ပွိုင့်/ဆက်တိုက်ဇယား၊ ဝင်ငွေဇယား မဟုတ်ပါ။ ',
  tokenMtcCompliance: '⚠️ MTC ပရိသတ်ပွိုင့်သည် ပလက်ဖောင်းပွိုင့်သာ: ငွေထုတ်မရ · လွှဲမရ · ရောင်းဝယ်မရ · ဝင်ငွေ အာမမခံ · ဘဏ္ဍာရေးပိုင်ဆိုင်မှု မဟုတ် · လောင်းကစား မချိတ်ဆက်။',
  tokenInsufficient: 'MTC မလုံလောက်ပါ',

  // Community
  communityBack: '👥 VIP',
  vipKicker: 'VIP',
  vipPriceSub: 'သင်ရရှိသည်မှာ ခန့်မှန်းတစ်ခု မဟုတ်ဘဲ ပွဲသတင်း တစ်ခုလုံးဖြစ်သည်။',
  communityTitle: 'အသိုင်းအဝိုင်း',
  statusComingSoon: 'မကြာမီ',
  statusActive: 'ကြည့်ရန်',
  statusDisabled: 'မဖွင့်သေး',
  intelFlowTitle: 'သတင်း တစ်ခုလုံး',
  flow1T: 'ပွဲမတိုင်ခင် မော်ဒယ်',
  flow1D: 'ပွဲတိုင်း၏ နိုင်ခြေ၊ အကြံပြုရမှတ်၊ အန္တရာယ်အဆင့်နှင့် အဓိကအချက်များ။',
  flow2T: 'ပွဲချိန် လူစာရင်းပြင်',
  flow2D: 'လူစာရင်းထွက်ပြီး ၃၀ မိနစ်အတွင်း AI ပြန်တွက်ပြီး ပြောင်းလဲမှု ပို့သည်။',
  flow3T: 'ပွဲပြီး ပြန်သုံးသပ်',
  flow3D: 'မော်ဒယ်နှင့် တကယ့်ရလဒ် နှိုင်းယှဉ်ပြီး နောက်ပွဲအတွက် အမြင် စုဆောင်းသည်။',
  benefitsTitle: 'အကျိုးခံစားခွင့်',
  benefit1: 'နေ့စဉ် AI သတင်း ၃-၅ ပွဲ',
  benefit2: 'တစ်ပွဲ မော်ဒယ်ရှင်းလင်းချက် အပြည့်',
  benefit3: 'လူစာရင်းထွက်ပြီး ၃၀ မိနစ်အတွင်း AI ပြန်တွက်',
  benefit4: 'တိုက်ရိုက်ပြင်ဆင်ချက် real-time',
  benefit5: 'အန္တရာယ်မြင့် ပွဲ သတိပေး',
  benefit6: 'MTC ပွိုင့် ဆုကြေး',
  benefit7: 'သီးသန့် အသိုင်းအဝိုင်း ဝန်ဆောင်မှု',
  whyVipTitle: 'အသိုင်းအဝိုင်း ဘာကြောင့် တန်ဖိုးရှိ?',
  whyVipExample: 'real-time ပြောင်းလဲမှု ဥပမာ',
  whyVipHomeRate: 'Brazil နိုင်ခြေ',
  whyVipReason: 'Argentina အဓိက ခံစစ်လူ မပါ → Brazil ညာတောင်ပံ အသာစီး၊ အသိုင်းအဝိုင်းကို ပထမဆုံး ပို့သည်။',
  csTitle: 'AI အကြောင်းအရာ စတူဒီယို',
  csStatus: 'ဒေတာ တည်ဆောက်နေဆဲ',
  csItem1: 'ယနေ့ AI ၃ ပွဲ အမြန်ကြည့်',
  csItem2: 'ယနေ့ ယုံကြည်မှု အမြင့်ဆုံး',
  csItem3: 'အံ့အားသင့် ပုံတို',
  csItem4: 'တိုက်ရိုက်ပြင် screenshot',
  csItem5: 'ပွဲပြီး ပြန်သုံးသပ် ပုံရှည်',
  csItem6: 'အသိုင်းအဝိုင်း content',
  csAction1: 'လုပ်ငန်း content ကူး (မကြာမီ)',
  csAction2: 'မျှဝေကတ် ဖန်တီး (မကြာမီ)',
  storageConnected: 'အရင်းအမြစ် သိမ်းဆည်း ချိတ်ပြီး',
  storagePublicEnabled: 'အများသုံး ဝင်ရောက်မှု ဖွင့်ပြီး',
  storagePublicPending: 'အများသုံး domain စောင့်ဆိုင်း',
  storageChecking: 'သိမ်းဆည်းမှု status စစ်ဆေးနေ',
  subscribeNowLabel: 'အခု စာရင်းသွင်းရန်',
  subscribedLabel: '✓ စာရင်းသွင်းပြီး · push ဖွင့်ပြီး',
  subscribedToast: 'စာရင်းသွင်းအောင်မြင် · push ဖွင့်ပြီး',
  alreadySubscribed: 'စာရင်းသွင်းပြီး',
  communityMutedNote: 'စာရင်းသွင်းမှုသည် AI ဒေတာ ခွဲခြမ်းစိတ်ဖြာမှု ဝန်ဆောင်မှု · လောင်းကစား မဟုတ် · ငွေသား မလက်ခံ · MTC ငွေထုတ်မရ',

  // Report page
  reportBack: 'မော်ဒယ် နည်းဗျူဟာခန်း',
  reportUnlocked: '🔓 ဖွင့်ပြီး',
  reportVerdictTitle: 'AI နောက်ဆုံး ဆုံးဖြတ်ချက်',
  keyFactorsTitle: 'အဓိက အချက် ပါဝင်မှု',
  riskRadarTitle: 'အန္တရာယ် radar',
  radarForm: 'လတ်တလော ဖောင်း',
  radarSquad: 'အသင်း ပြည့်စုံမှု',
  radarTactical: 'နည်းဗျူဟာ ယှဉ်ပြိုင်',
  radarLive: 'ပွဲချိန် ပြောင်းလဲမှု',
  radarNote: 'မော်ဒယ်က နာမည်ကြီးမှုကို မကြည့်ဘဲ လတ်တလောဖောင်း၊ အသင်းပြည့်စုံမှု၊ နည်းဗျူဟာ ယှဉ်ပြိုင်မှုနှင့် ပွဲချိန်ပြောင်းလဲမှုကို နှိုင်းယှဉ်သည်။',
  tacticsTitle: 'နည်းဗျူဟာ ရှင်းလင်းချက်',
  trendTitle: 'နှုန်း ပြောင်းလဲမှု',
  lwLogTitle: 'ပွဲချိန် ပြင်ဆင်မှု မှတ်တမ်း',
  lwDrawProb: 'သရေ ဖြစ်နိုင်ခြေ',
  lwChangeReason: 'ပြောင်းလဲရသည့် အကြောင်းရင်း: ',
  reportSubscribeCta: 'အသိုင်းအဝိုင်း စာရင်းသွင်းရန် · ပွဲတိုင်း ပွဲချိန်ပြင်ဆင်ချက် push',
  tgSheetTitle: 'Telegram ဖွင့်နည်း',
  tgOpen: 'Telegram ဖွင့်ရန်',
  tgCopy: 'Link ကူးရန်',
  tgHint: 'မဖွင့်နိုင်ပါက link ကို copy လုပ်ပြီး Telegram app သို့မဟုတ် browser ထဲတွင် paste လုပ်ပါ။',
  tgCopied: 'Link ကူးပြီး',
  tgClose: 'ပိတ်ရန်',

  // Compliance
  mtcStatement: 'MTC သည် ပလက်ဖောင်းပွိုင့်သာဖြစ်ပြီး ငွေထုတ်မရ၊ လွှဲမရ၊ ရောင်းဝယ်မရ၊ ဘဏ္ဍာရေးပိုင်ဆိုင်မှု မဟုတ်ပါ။',
  disclaimer: 'အတိတ်စွမ်းဆောင်ရည်သည် အနာဂတ်ရလဒ်ကို အာမမခံပါ။ ဒေတာ ခွဲခြမ်းစိတ်ဖြာမှုနှင့် ဘောလုံး ဖျော်ဖြေရေးအတွက်သာ။',
  complianceFooter: 'AI ဒေတာ ခွဲခြမ်းစိတ်ဖြာမှုသာ · လောင်းကစား ဝန်ဆောင်မှု မဟုတ် · ငွေသား မလက်ခံ · MTC ငွေထုတ်မရ',
};
